[features]
seeds = false
[programs.localnet]
staking_factory = "DBa1q9iY3ZrvXBgEpVq453adWqZUrVDmRQztiW6FRJek"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/max/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
